name: Build Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Do not run if the only files changed cannot affect the build
    paths-ignore:
      - "**.md"
      - "**.pro"
      - "**.sh"
      - "**.perl"
      - ".github/CODEOWNERS"
      - ".circleci/config.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build_ldas_ifort:
    name: Build GEOSldas with ifort
    if: "!contains(github.event.pull_request.labels.*.name, '0 diff trivial')"
    runs-on: ubuntu-24.04
    container:
      image: gmao/ubuntu24-geos-env:v7.32.0-intelmpi_2021.13-ifort_2021.13

    env:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_btl_vader_single_copy_mechanism: none

    steps:
      # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout LDAS
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          filter: blob:none
          repository: GEOS-ESM/GEOSldas

      - name: Set all directories as git safe
        run: |
          git config --global --add safe.directory '*'

      - name: Versions etc.
        run: |
          ifort --version
          mpirun --version
          echo $BASEDIR

      - name: Mepo clone external repos
        run: |
          mepo clone --partial blobless
          mepo status

      - name: Update other branches
        if:
          "!contains('refs/heads/main,refs/heads/develop', github.ref)"
        run: |
          mepo checkout-if-exists ${GITHUB_HEAD_REF}
          mepo status

      - name: CMake
        run: |
          cmake -B build -S . --install-prefix=${pwd}/install -DCMAKE_Fortran_COMPILER=ifort -DCMAKE_BUILD_TYPE=Debug -DMPIEXEC_PREFLAGS='--oversubscribe' -DUSE_F2PY=OFF

      - name: Build
        run: |
          cmake --build build -j 4
          cmake --install build


  build_ldas_gfortran:
    name: Build GEOSldas with gfortran
    if: "!contains(github.event.pull_request.labels.*.name, '0 diff trivial')"
    runs-on: ubuntu-24.04
    container:
      image: gmao/ubuntu24-geos-env-mkl:v7.32.0-openmpi_5.0.5-gcc_14.2.0

    env:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_btl_vader_single_copy_mechanism: none

    steps:
      # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout LDAS
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          filter: blob:none
          repository: GEOS-ESM/GEOSldas

      - name: Set all directories as git safe
        run: |
          git config --global --add safe.directory '*'

      - name: Versions etc.
        run: |
          gfortran --version
          mpirun --version
          echo $BASEDIR

      - name: Mepo clone external repos
        run: |
          mepo clone --partial blobless
          mepo status

      - name: Update other branches
        if:
          "!contains('refs/heads/main,refs/heads/develop', github.ref)"
        run: |
          mepo checkout-if-exists ${GITHUB_HEAD_REF}
          mepo status

      - name: CMake
        run: |
          cmake -B build -S . --install-prefix=${pwd}/install -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Debug -DMPIEXEC_PREFLAGS='--oversubscribe' -DUSE_F2PY=OFF

      - name: Build
        run: |
          cmake --build build -j 4
          cmake --install build
